version: '3.8'
services:
  stats-client:
    build: ./ewm-stats-service/stats-client
    image: ewm-stats-client-image
    container_name: stats-client-container
    ports:
      - "9090:9090"
    environment:
      - stats-client-port=9090
      - stats-server.url=http://stats-server:9093
    depends_on:
      - stats-server

  stats-server:
    build: ./ewm-stats-service/stats-server
    image: ewm-stats-server-image
    container_name: stats-server-container
    depends_on:
      - stats-db
    environment:
      - stats-server-port=9093
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    hostname: stats_db

  ewm-service:
    build: ./ewm-main-service
    image: ewm-main-server-image
    container_name: ewm-main-server-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - ewm-server-port=8080
      - stats-server.url=http://stats-client:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db:5432/ewm
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    hostname: ewm_db