    CREATE TABLE IF NOT EXISTS hits(
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                app VARCHAR(255) NOT NULL,
                                uri VARCHAR(700) NOT NULL,
                                ip VARCHAR(32) NOT NULL,
                                time_stamp TIMESTAMP WITHOUT TIME ZONE
);
CREATE INDEX hits_app_field ON hits (app);
CREATE INDEX hits_uri_fields ON hits (uri);
CREATE INDEX hits_ip_fields ON hits (ip);
CREATE INDEX hits_time_stamp_fields ON hits (time_stamp);